### ISSUE TITLE
add support

### ISSUE THREAD

**Issue by slideray** [emacscollective/no-littering#110]
please add support package
"auto-package-update"
It's create file `.emacs.d/.last-package-update-day`.

Thanks for you amazing project!

**Comment by tarsius** [comment]
Please implement that yourself and then open a pull-request.

**Comment by slideray** [comment]
Sorry, I don't know how to use github, and I'm not a programmer, I don't even know what it is pull-request.

I solved the problem as follows:
```
(use-package no-littering
  :ensure t
  :config
  (setq auto-package-update-last-update-day-filename
	(expand-file-name (format-time-string "data/.last-package-update-day") tmp-files-dir)))
```
