### ISSUE TITLE
[Question] Is gnus-home-directory themable?

### ISSUE THREAD

**Issue by condy0919** [emacscollective/no-littering#142]
The default value of `gnus-home-directory` is `~/` which is not located at `~/.emacs.d/`.

**Comment by tarsius** [comment]
All the variables whose default values depend on the value of this variable should be changed in the same commit; in our case without referring to the value of this variable. Some of these files should go into var, others into etc. This variable itself has to be set for the benefit of future variables. It should probably point to a directory inside etc.

**Comment by tarsius** [comment]
Hm wait... maybe we should only theme `gnus-directory`. I partially confused the two.

In any case, all the relevant variables should be themed at the same time and the commit message should carefully describe the rational. Please do that and I will then decide if I agree, require more information, or have another proposal.

**Comment by condy0919** [comment]
There are amount of variables of Gnus to be themed. Let me figure out all the variables..

**Comment by fernandodemorais-jf** [comment]
Hello,

Sorry for commenting in a already closed issue, but I have some questions related to this topic.

Recently I've been thinking about how to theme Gnus relevant dirs properly.
By reading `no-littering.el` guidelines I came up with this:

```emacs-lisp
(setq gnus-home-directory                     (etc "gnus/"))
(setq gnus-directory                          (etc "gnus/"))
(setq gnus-init-file                          (etc "gnus/init.el"))
(setq gnus-startup-file                       (etc "gnus/startup/newsrc"))
(setq gnus-cache-directory                    (var "gnus/cache/"))
(setq message-directory                       (etc "message/"))
(setq message-signature-directory             (etc "message/signature/"))
(setq message-auto-save-directory             (var "message/auto-save/"))
```

Normally `gnus-directory` and `message-directory`, with their default values, creates the `~/News` and `~/Mail` folders, respectively.

So, my doubt is:

The correct paths, following `no-littering.el` specifications, is like above or is more like bellow?

```emacs-lisp
(setq gnus-home-directory                     (etc "gnus/"))
(setq gnus-directory                          (etc "gnus/news/"))           ; As the default.
(setq gnus-init-file                          (etc "gnus/init.el"))
(setq gnus-startup-file                       (etc "gnus/startup/newsrc"))
(setq gnus-cache-directory                    (var "gnus/news/cache/"))     ; As the default.
(setq message-directory                       (etc "message/mail/"))        ; As the default.
(setq message-signature-directory             (etc "message/signature/"))
(setq message-auto-save-directory             (var "message/mail/drafts/")) ; As the default.
```

Thanks!

**Comment by tarsius** [comment]
> Normally `gnus-directory` and `message-directory`, with their default values, creates the `~/News` and `~/Mail` folders, respectively.

I probably wouldn't change that. That's actual content. Not configuration (`etc`) or generated persistent data (`var`).
