### ISSUE TITLE
Save place mode not working with no-littering

### ISSUE THREAD

**Issue by bataak** [emacscollective/no-littering#169]
`save-place-mode` is not working with no-littering.

Here is my additional config:
```
(setq auto-save-file-name-transforms
      `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))
```

Thanks!

**Comment by tarsius** [comment]
We already mention that in the documentation. :smile_cat: 

https://github.com/emacscollective/no-littering#auto-save-settings
