### ISSUE TITLE
Any thought for adding XDG compliance?

### ISSUE THREAD

**Issue by duckwork** [emacscollective/no-littering#171]
This would be a little more involved that simply setting `no-littering-etc-directory` to `$XDG_CONFIG_HOME/emacs`, and `no-littering-var-directory` to `$XDG_DATA_HOME/emacs`, because there's also some cache files that would need to go somewhere in `$XDG_CACHE_HOME`.

Plus, where would the files in ~/.config/emacs/ go? In ~/.config/emacs/etc/ ?

Anyway I think this is worth considering but it is kind of tricky.

Should it be another package altogether?

**Comment by tarsius** [comment]
Changes are being made to Emacs. See messages after (and maybe before) https://lists.gnu.org/archive/html/emacs-devel/2021-10/msg01879.html. `no-littering` was mentioned. I think this goes into the right direction but some persistence will be necessary to go beyond a 80% solution. I do not have the motivation to do that now but I am confident to get around to it before the feature freeze for Emacs 29.1. Forgive me for not outlying my thoughts on the matter now; I plan to do that eventually, just not now.

**Comment by duckwork** [comment]
No worries! I just had the thought --- I thought it'd be non-trivial. I mean, `no-littering`'s line count attests to that!

Anyway, I'll monitor the mailing list for more information here; thanks for the information!
