### ISSUE TITLE
Native code compilation cache example not relevant to Emacs 28.1

### ISSUE THREAD

**Issue by mkoloberdin** [emacscollective/no-littering#181]
Perhaps it's worth mentioning in the readme that the native code compilation cache snippet won't work on the current stable version of Emacs (28.1) since the required function (`startup-redirect-eln-cache`) was added only recently and is not present in 28.1: https://github.com/emacs-mirror/emacs/commit/d3c47011d5ace1e1c3fca830d3ff71d9c693ed5d

**Comment by tarsius** [comment]
Done. Thanks!
