### ISSUE TITLE
recentf exclude is not working

### ISSUE THREAD

**Issue by jvillasante** [emacscollective/no-littering#199]
The documentation mentions the following in order to exclude no-littering directories from `recentf` mechanism:

```
(require 'recentf)
(add-to-list 'recentf-exclude no-littering-var-directory)
(add-to-list 'recentf-exclude no-littering-etc-directory)
```

That was not working for me and I had to do the following instead:

```
(require 'recentf)
(add-to-list 'recentf-exclude (recentf-expand-file-name no-littering-var-directory))
(add-to-list 'recentf-exclude (recentf-expand-file-name no-littering-etc-directory))
```

Maybe the documentation should be updated or I'm missing something?

**Comment by tarsius** [comment]
That was caused by a backward incompatible change in Emacs 29.

Thanks for the report.
