### ISSUE TITLE
Add a flow chart for "Conventions"

### ISSUE THREAD

**Issue by yantar92** [emacscollective/no-littering#217]
Almost every time I submitted (or considered to submit) a pull request here, I somehow had difficulties obeying the conventions.

I cannot say that conventions are not clear or not detailed enough, but it keeps hapenning.

I believe that a simple flow chart (decision tree) will help people to go conform conventions.

WDYT?

**Comment by tarsius** [comment]
> Almost every time I submitted (or considered to submit) a pull request
> here, I somehow had difficulties obeying the conventions.

I hope you are not to annoyed and/or embarrassed by that.

Please don't be discouraged by this from theming more packages.  It's not like I get so many pull-requests that failure to follow the conventions to the letter would cause me much grief.

> I cannot say that conventions are not clear or not detailed enough,
> but it keeps hapenning.
> 
> I believe that a simple flow chart (decision tree) will help people to
> go conform conventions.
> 
> WDYT?

I am not sure that would really help.  (How would it differ from just drawing arrows from one bullet point to the next.)

And of course it is work to create that and then keep it in sync with the conventions in list form, which I would rather avoid.  I expect it would be more work to maintain the flow chart than it is to occasionally correct a submission.

I've looked at your past submission and don't think a flow chart would have helped.  It doesn't look like you overlooked some convention (except here not dropping `-file`) but that you just happened to run into special cases that I had not created a convention for yet.

The current list of conventions might already seem arbitrary and excessive to some potential contributor.  Additionally adding a flow chart would scream "you better make sure you don't mess this up".  I think I would rather go the other way and a remark to the effect of "please try to follow the conventions but if you are unsure then just submit what you have and I will correct it if necessary, without biting your head of".

**Comment by yantar92** [comment]
> I think I would rather go the other way and a remark to the effect of "please try to follow the conventions but if you are unsure then just submit what you have and I will correct it if necessary, without biting your head off".

That would also help.

FYI, the lengthy pull request template already created an impression that "you better make sure you don't mess this up".

**Comment by tarsius** [comment]
I haven't read that in a while.

I've just removed the paragraph that was a bit over the top and clearly written while being annoyed by a string of sloppy contributions. Let's see what effect that has before potentially *adding* a note about not removing any heads.

![main-qimg-5a1bf844e19dff6bafea8fa718fc5732-lq](https://github.com/emacscollective/no-littering/assets/25046/cae465df-ebc9-4dfc-bbc4-d48bab5af10d)
