### ISSUE TITLE
[Feature Request] eFar file manager

### ISSUE THREAD

**Issue by AndersonTorres** [emacscollective/no-littering#240]
The package [eFar](https://github.com/suntsov/efar) provides a [FAR](https://github.com/FarGroup/FarManager)-like file manager for Emacs.

Bumping on it to experiment a little bit, I noticed it creates a hidden file, namely `.efar-state`. Digging the code, I found this line:

https://github.com/suntsov/efar/blob/78618a6cd9fe7d46c3728db3589d1fe50f7c1c6b/efar.el#L147

Is this a good opportunity to add eFar to no-littering?

**Comment by tarsius** [comment]
Sure. Likely like so: `(setq efar-state-file-name (var "efar-state"))`. Please open a pull-request.
