### ISSUE TITLE
FYI no-littering is marked as obsolete today via normal package update

### ISSUE THREAD

**Issue by shipmints** [emacscollective/no-littering#242]
I have a feeling this is due to expired/changed signing keys/fingerprint?

<img width="1303" alt="image" src="https://github.com/user-attachments/assets/8bbcb160-fea9-4ad5-aead-55c5c659adcc">

**Comment by tarsius** [comment]
Thanks for bothering to inform me, but I don't think there is anything I can do about it. I don't use `package.el` myself and don't know if this even is a problem. I *think* what this means is that *this* version of the package is installed but isn't the latest available version and that somewhere else in the list another version is listed as the current version. After you have updated the package, there is only one entry and it isn't listed as obsolete.

**Comment by shipmints** [comment]
I think this was a red herring as I just now noticed when I refreshed packages that there were additional new releases since I last upgraded ```no-littering``` and I just picked the latest and obsoleted the older ones. Cheers and thanks for the package.
