### ISSUE TITLE
There is no explanation behind var and etc logic

### ISSUE THREAD

**Issue by Fuco1** [emacscollective/no-littering#78]
- What exactly should go into var?
- What exactly should go into etc?

**Comment by tarsius** [comment]
Are you talking about the directories or the local functions?

Isn't this enough to document the directories?:

> The default paths used to store configuration files and persistent
> data are not consistent across Emacs packages. [...]
> This package sets out to fix this by changing the values of path
> variables to put files in either `no-littering-etc-directory`
> (defaulting to `~/.emacs.d/etc/`) or `no-littering-var-directory`
> (defaulting to `~/.emacs.d/var/`),

It doesn't really say that `etc` is used for configuration files and `var` for persistent data, but the order is the same in both places. Maybe you could submit a pr that makes this more obvious, if you think that really is necessary.

Isn't this enough to "document" the functions?:

```lisp
(cl-letf (((symbol-function 'etc)
           (symbol-function #'no-littering-expand-etc-file-name))
          ((symbol-function 'var)
           (symbol-function #'no-littering-expand-var-file-name)))
```

**Comment by Fuco1** [comment]
I'm indeed talking about what should be placed in which directory not the functions.  Now that you point out the section it is a bit cleaner what the "put files" refers to, but it wasn't obvious to me on the first read.
