### ISSUE TITLE
no-littering breaks savehist-mode

### ISSUE THREAD

**Issue by mrbig033** [emacscollective/no-littering#88]
* MX Linux
* GNU Emacs 27.0.50
* no-littering-20181030.1247/
* [init](https://gitlab.com/mrbig/emacs/blob/master/init.org)

When `no-littering` is enabled, `savehist-mode t` doesn't work.

**Comment by mrbig033** [comment]
The following configuration solves the problem:

```
(use-package savehist
:config
(savehist-mode t))

(use-package no-littering
:after savehist
:ensure t)
```

**Comment by mrbig033** [comment]
I added `(setq savehist-file "~/.emacs.d/var/savehist.el")` to savehist as such:

```
(use-package savehist
:init
(setq savehist-file "~/.emacs.d/var/savehist.el")
:config
(setq history-length 500)
(setq savehist-additional-variables '(kill-ring search-ring))
(savehist-mode t))
```
And I think it's working now. I'll reopen if there's a change.

**Comment by gety9** [comment]
@alienbogart i know it's super old thread, but are your still using similar config for savehist and no littering?
(i have problems with savehist on emacs 29)

**Comment by tarsius** [comment]
The readme now contains information concerning these features: https://github.com/emacscollective/no-littering#auto-save-backup-and-undo-tree-files.
